# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/mamughal/Desktop/Game/Game.cache/wt [current_project]
set_property parent.project_path C:/Users/mamughal/Desktop/Game/Game.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/mamughal/Desktop/Game/Game.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/mamughal/Desktop/Game/Game.srcs/sources_1/imports/new/Whack_a_Mole_Game.v
  C:/Users/mamughal/Desktop/Game/Game.srcs/sources_1/imports/new/add3.v
  C:/Users/mamughal/Desktop/Game/Game.srcs/sources_1/imports/new/bcd7seg.v
  C:/Users/mamughal/Desktop/Game/Game.srcs/sources_1/imports/new/binary_to_BCD.v
  C:/Users/mamughal/Desktop/Game/Game.srcs/sources_1/imports/new/decoder2to4.v
  C:/Users/mamughal/Desktop/Game/Game.srcs/sources_1/imports/new/gameTimer.v
  C:/Users/mamughal/Desktop/Game/Game.srcs/sources_1/imports/new/mux4to1.v
  C:/Users/mamughal/Desktop/Game/Game.srcs/sources_1/imports/new/my_counter.v
  C:/Users/mamughal/Desktop/Game/Game.srcs/sources_1/imports/new/slowclock.v
  C:/Users/mamughal/Desktop/Game/Game.srcs/sources_1/imports/new/timerCount.v
  C:/Users/mamughal/Desktop/Game/Game.srcs/sources_1/imports/new/Top_Module.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/mamughal/Desktop/Game/Game.srcs/constrs_1/new/Game.xdc
set_property used_in_implementation false [get_files C:/Users/mamughal/Desktop/Game/Game.srcs/constrs_1/new/Game.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top_Module -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Module.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Module_utilization_synth.rpt -pb Top_Module_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
